<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\omega-vpn.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Omega.Client.App.Core\Omega.Client.App.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\omega-vpn.ico" />
    <Resource Include="Assets\omega-vpn.png" />
  </ItemGroup>
</Project>
